### ISSUE TITLE
Suggestion for README

### ISSUE THREAD

**Issue by coltenkrauter** [cdklabs/cdk-nextjs#13]
Hey there! 👋

Just starting out with this package and really like it—awesome work! I have a few suggestions for enhancing the README.

1. **Add Next.js Project Setup**  
   It would be helpful to include a step for setting up a Next.js project for those who don’t already have one. Maybe something like:  
   > "If you don’t have a Next.js project yet, follow [these steps](https://nextjs.org/docs/getting-started) to create one."

1. **Is docker required?**
   Step 1 indicates,
   > Install [Docker](https://www.docker.com/).

   Is this required even for non-container deployments?

1. **Clarify Global vs. Regional Containers**  
   The diagrams are super helpful, but some short explanations would make them even clearer. It would help to know:
   - What’s the difference between **global functions**, **global containers**, and **regional containers**?
   - What are the trade-offs/considerations between these options?
   For example, pros for serverless,
      - **AWS Lambda** only charges for actual compute time, which is great for sites with variable traffic.
      - It keeps things simple—no need to manage containers unless absolutely necessary.

1. **Expand on Overrides**  
   More details on **overrides** would be super useful. A couple of examples showing how to tweak deployments would really help users understand how to use this feature.

1. **Custom DNS Setup**  
   A section on how to set up **custom DNS** would be a huge help. You could include steps to connect a custom domain or even a full example.

---

Thanks again for creating this package! If you’re open to it, I’d be happy to submit a Pull Request to cover some of these suggestions. 😊

Cheers! 🎉

**Comment by bestickley** [comment]
Hey @coltenkrauter! Glad you like it. Thank you very much for the suggestions. PRs are welcome :)

1. Agreed.
2. Yes
3. Agreed, I have some more thoughts here.
4. Yes, I think an example would be most effective here. There are hundreds of potential options to override.
5. Yes, again, I think an example app would be great.
