### ISSUE TITLE
S3Origin Is On Deprecation Path

### ISSUE THREAD

**Issue by coltenkrauter** [cdklabs/cdk-nextjs#15]
I observed this warning while deploying,

```
Warning:  aws-cdk-lib.aws_cloudfront_origins.S3Origin is deprecated.
  Use `S3BucketOrigin` or `S3StaticWebsiteOrigin` instead.
  This API will be removed in the next major release.
```

Here is where it is in this code: [src/nextjs-distribution.ts#L176-L178](https://github.com/cdklabs/cdk-nextjs/blob/7e289a1db5ec49382c86bd9622710eb965046c85/src/nextjs-distribution.ts#L176-L178).

---

![Screenshot 2024-10-12 at 12 09 29 AM](https://github.com/user-attachments/assets/92843448-5b09-4342-8e89-e7f7bf4a6369)

**Comment by bestickley** [comment]
@coltenkrauter, thanks the raising this. I'll be handling this in my next PR.
