### ISSUE TITLE
AWS_NODEJS_CONNECTION_REUSE_ENABLED doesn't exist in V3

### ISSUE THREAD

**Issue by coltenkrauter** [cdklabs/cdk-nextjs#25]
I stumbled on [this (`AWS_NODEJS_CONNECTION_REUSE_ENABLED doesn't exist in V3`)](https://github.com/aws/aws-sdk-js-v3/issues/5883). 

I saw it was used [here in SignFnUrlFunction – src/lambdas/sign-fn-url/sign-fn-url-function.ts#L24C26-L24C61](https://github.com/cdklabs/cdk-nextjs/blob/7e5a1ba955a2c1981c8dc35b180dc02465e4b7af/src/lambdas/sign-fn-url/sign-fn-url-function.ts#L24C26-L24C61) so I made this issue for awareness, I expect we may want to change this at some point since `AWS_NODEJS_CONNECTION_REUSE_ENABLED` isn't supported in v3.

**Comment by bestickley** [comment]
Thanks for reporting, @coltenkrauter! I'll address this in upcoming PR.
