### ISSUE TITLE
Log Group Adjustments (Names/Retention/RemovalPolicy)

### ISSUE THREAD

**Issue by coltenkrauter** [cdklabs/cdk-nextjs#26]
I am interested in changing some default log group props, so I am kicking off a discussion about it.

### 1. Names
Here are some log groups that are created when I spin up `NextjsGlobalFunctions` (An example of my stack can be seen [here](https://github.com/cdklabs/cdk-nextjs/issues/16#issuecomment-2466572676)).

```zsh
# Numbered for easier discussion....
# Note, I named the stack "Web" and the NextJs construct "Nebula" so this will differ for each project.

# CURRENT

/aws/lambda/Web-AWS679f53fac002430cb0da5b7982bd22872D-0DuPsyORgbhL		# 1. Not sure what this one is for
/aws/lambda/Web-CustomS3AutoDeleteObjectsCustomResour-Muomtw8ahBtp		# 2
/aws/lambda/Web-NebulaNextjsAssetsDeploymentFn36251C3-AfNzwSrXnrYx		# 3 
/aws/lambda/Web-NebulaNextjsFunctions5D2EB29D-H6Lw7s5Cdf4U			# 4
/aws/lambda/us-east-1.Web-NebulaNextjsDistributionSignFnUrlFCEE-0L79iHzRNlk3	# 5

# PROPOSAL – I would propose defaults that omit the ID at the end and indicate the construct name

/aws/lambda/Web-Nebula-AWS				# 6
/aws/lambda/Web-Nebula-S3AutoDeleteObjects		# 7
/aws/lambda/Web-Nebula-NextjsAssetsDeployment		# 8 
/aws/lambda/Web-Nebula-NextjsFunctions			# 9
/aws/lambda/Web-Nebula-NextjsDistribution		# 10 
```

### 2. Retention

Right now, all the log groups get created with retention of `Never expire`. I propose setting this to a default of 1 or 2 years.

### 3. Removal Policy

I recently redeployed the `NextjsGlobalFunctions` and seemingly most of the LogGroups did not automatically delete (which is desired in non-prod environments), so I ended up seeing duplicated log groups, just with a different ID on the end.

I lean toward setting a removal policy of `DESTROY` that can be overridden as desired.

---

Now, I expect that some of the log groups that I mentioned above are being created uth (under the hood)... For example, the [SignFnUrlFunction](https://github.com/cdklabs/cdk-nextjs/blob/7e5a1ba955a2c1981c8dc35b180dc02465e4b7af/src/lambdas/sign-fn-url/sign-fn-url-function.ts#L15C14-L25) doesn't specify a log group, so one is created uth. Also, I noticed that there does not appear to be an option for that function to supply overrides. 

My suggestion for how this could be implemented would be to,
1. Add support for overrides to constructs related to the log groups I list above
2. Create a log group function `getLogGroup(name)` the creates and returns a log group with the desired defaults and then use _that_ as the default log group for the different constructs.

**Comment by bestickley** [comment]
Hey @coltenkrauter, thanks for raising this issue! CDK [recommends](https://docs.aws.amazon.com/cdk/v2/guide/best-practices.html) using those generated names with random characters. This is so that you don't have naming collisions. If we named the log groups statically as you suggested, then a 2nd deployment of the same cdk-nextjs app would fail.

I 100% agree with providing overrides for all constructs. By doing this, consumers of this lib should be able to update any log property they want. Aren't we already doing this?

As for default retention, I think we should stick with the default the CDK is using. You're welcome to customize the log retention to suite your app's needs. You could even create a CDK Aspect to change retention on all log groups if you want.

Based on my above response, I don't see any action here. Do you agree? If so, I'll close the issue. Let me know!

**Comment by coltenkrauter** [comment]
Those are fair points. I am in agreement with you to leave the defaults as is. That said, I want to make some of these changes for my stacks. 

The only outstanding discussion would be related to removal policy. I personally would like the default removal policy to be `DESTROY`, but I am highly flexible on this. (I can do it for myself with overrides)

How about we close out this issue and I will create another issue for any overrides that I want support for.

**Comment by coltenkrauter** [comment]
> I 100% agree with providing overrides for all constructs. By doing this, consumers of this lib should be able to update any log property they want. Aren't we already doing this?

I think I may have been mistaken when I said,

> I noticed that there does not appear to be an option for that function to supply overrides.

---

I think I was looking in the wrong spot. I've since found the overrides.
