### ISSUE TITLE
Consider the TypeScript Partial Type

### ISSUE THREAD

**Issue by coltenkrauter** [cdklabs/cdk-nextjs#27]
I noticed in the codebase that there’s a directory of generated structs `src/generated-structs`. Files like `OptionalFunctionProps.ts`, for example, define interfaces where most properties are optional. 

```typescript
// Example
export interface OptionalFunctionProps {
  readonly runtime?: aws_lambda.Runtime;
  readonly handler?: string;
  readonly code?: aws_lambda.Code;
  // ...
}
```

I was wondering if instead of defining these explicitly, we could replace the `OptionalFunctionProps` entirely by using [Typescript Partial Type](https://www.typescriptlang.org/docs/handbook/utility-types.html#partialtype) like this `Partial<FunctionProps>` directly in usage. This would eliminate the need for separate optional interfaces and keep the code more concise.

```typescript
// BEFORE
export interface NextjsDistributionOverrides {
  readonly edgeFunctionProps?: OptionalFunctionProps;
  readonly distributionProps?: OptionalDistributionProps;
  // ...

// AFTER
export interface NextjsDistributionOverrides {
  readonly edgeFunctionProps?: Partial<FunctionProps>; // FunctionProps imported from aws-cdk-lib
  readonly distributionProps?: Partial<DistributionProps>; // DistributionProps imported from aws-cdk-lib
  // ...
```

By using `Partial<>`, we reduce redundancy and the risk of mismatches, as updates to the base interface are automatically applied. 

---

## Questions
1. How are the optional types currently generated, and is the process flexible enough to replace these optional interfaces with direct usage of `Partial<T>`?
2. Is there a reason not to use the [TypeScript Partial Type](https://www.typescriptlang.org/docs/handbook/utility-types.html#partialtype)?

**Comment by bestickley** [comment]
@coltenkrauter, I wish we could! See here for why not: https://github.com/mrgrain/jsii-struct-builder. That link will answer both of your questions.

**Comment by coltenkrauter** [comment]
Ah darn... I'm not surprised that there is a good reason. Still a bummer 🌵
